name: Deploy Playground repository

on:
  push:
    branches: ["deploy"]

permissions: {}

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Compile Playground repository
        uses: jku/repository-playground/playground/actions/compile@git-repo-deploy
        with:
          path: compiled-metadata/
      - name: Upload repository for GitHub Pages
        uses: actions/upload-pages-artifact@253fd476ed429e83b7aae64a92a75b4ceb1a17cf
        with:
          path: compiled-metadata/

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Playground repository to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@0243b6c10d06cb8e95ed8ee471231877621202c0
