name: Signing event

permissions: {}

on:
  push:
    branches:
      - 'sign/**'
  workflow_dispatch:


jobs:
  handle-signing-event:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
      - name: Signing event
        uses: jku/repository-playground/playground/actions/signing-event@git-repo-impl
