name: Signing event

permissions: {}

on:
  push:
    branches:
      - 'sign/**'
  workflow_dispatch:


jobs:
  handle-signing-event:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
        with:
          python-version: 3.11
          cache: pip

      - name: Signing event
        uses: jku/repository-playground/playground/actions/signing-event@eaab68c53abe61d387c7d564a7673995957a65bb

