name: Signing event

permissions: {}

on:
  push:
    branches:
      - 'sign/**'
  workflow_dispatch:


jobs:
  handle-signing-event:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for commiting the snapshot/timestamp changes
      issues: write
      pull-requests: write
    steps:
      - name: Signing event
        uses: jku/repository-playground/playground/actions/signing-event@target-mgmt-v4

